recovery_behaviors:
  - name: 'conservative_reset'    
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

  - name: 'aggressive_reset'      
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

# recovery 세부 설정
conservative_reset:
  reset_distance: 4.0
  layer_names: ["laser_scan"]

aggressive_reset:
  reset_distance: 0.0            
  layer_names: ["laser_scan"]
