# global_costmap_params.yaml

global_costmap:
  global_frame: "map"
  robot_base_frame: "base_footprint"
  update_frequency: 1.0
  publish_frequency: 0.5
  transform_tolerance: 0.5
  static_map: true              # AMCL 사용을 위해 static_map: true로 변경
  rolling_window: true           # 글로벌도 rolling_window 사용
  width: 30.0
  height: 30.0
  resolution: 0.05

  # clearing 관련 파라미터 추가
  track_unknown_space: true
  unknown_cost_value: -1
  always_send_full_costmap: true
 